### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [prologic/msgbus#13]
I think if this project have a logotype, it will have more people ready to contribute.

If you want I can contribute with one for free, for that I need to know what do you want for your logo.

Greetings

**Comment by prologic** [comment]
I'm open to ideas :) What comes to mind for you? (*also thank you!*)

How about the Go mascot (*the Gopher*) shouting to other gophers? :P

**Comment by nunojesus** [comment]
My work is licensed under a [Creative Commons Attribution 4.0 International License.](creativecommons.org/licenses/by/4.0/)

So I have to have the premission to make something with Go mascot (the Gopher)

**Comment by prologic** [comment]
Feel free to re-open this if you still want to contribute a logl
